### ISSUE TITLE
HTTPError: 400 Client Error: Bad Request for url [neatocloud url]

### ISSUE THREAD

**Issue by ghost** [stianaske/pybotvac#30] opened 2018-12-09 15:42 UTC
_Coming from #29_

So after applying the quickfix in the aforementioned issue, I ran into this :

```python
Traceback (most recent call last):
  File "botvac.py", line 165, in <module>
    ui.setupUi(MainWindow)
  File "botvac.py", line 114, in setupUi
    robot = Robot('[REDACTED]','[REDACTED]',u'maps','[REDACTED]')
  File "/home/lili/.local/lib/python2.7/site-packages/pybotvac/robot.py", line 41, in __init__
    if self.service_version not in SUPPORTED_SERVICES:
  File "/home/lili/.local/lib/python2.7/site-packages/pybotvac/robot.py", line 213, in service_version
    return self.available_services['houseCleaning']
  File "/home/lili/.local/lib/python2.7/site-packages/pybotvac/robot.py", line 209, in available_services
    return self.state['availableServices']
  File "/home/lili/.local/lib/python2.7/site-packages/pybotvac/robot.py", line 205, in state
    return self.get_robot_state().json()
  File "/home/lili/.local/lib/python2.7/site-packages/pybotvac/robot.py", line 163, in get_robot_state
    return self._message({'reqId': "1", 'cmd': "getRobotState"})
  File "/home/lili/.local/lib/python2.7/site-packages/pybotvac/robot.py", line 60, in _message
    response.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://nucleo.neatocloud.com/vendors/neato/robots/[REDACTED]/messages
```

By any chance, is the SSL reversable with the cert and thus decryptable ? So I could get an idea of what is going on with Wireshark.

**Comment by fermulator** [comment] 2019-01-02 01:42
Hey, if you follow #18, do you get a similar more helpful error?

**Comment by RomRider** [comment] 2019-02-08 16:31
@fermulator this happens if your robot is offline while trying to instantiate it. PR #36 should fix the issue.

**Comment by fermulator** [comment] 2019-02-17 02:43
My device is not offline, so I don't think PR #36 is relevant here.

**Comment by fermulator** [comment] 2019-02-17 02:50
Upgraded to pybotvac latest
```
$ sudo pip3 install --upgrade pybotvac
Collecting pybotvac
  Downloading https://files.pythonhosted.org/packages/82/69/a8fee0104ec87d9778cc2ca85aa292d5607d5290362b584d5e9111015f6c/pybotvac-0.0.13-py3-none-any.whl
Installing collected packages: pybotvac
  Found existing installation: pybotvac 0.0.12
    Uninstalling pybotvac-0.0.12:
      Successfully uninstalled pybotvac-0.0.12
Successfully installed pybotvac-0.0.13
```

Same issue:
```
>>> import pybotvac
>>> for robot in pybotvac.Account('<e-mail-SNIPPED>', '<password-SINPPED>').robots: print(robot)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/account.py", line 64, in robots
    self.refresh_robots()
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/account.py", line 110, in refresh_robots
    endpoint=robot['nucleo_url']))
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/robot.py", line 43, in __init__
    if self.service_version not in SUPPORTED_SERVICES:
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/robot.py", line 226, in service_version
    return self.available_services['houseCleaning']
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/robot.py", line 222, in available_services
    return self.state['availableServices']
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/robot.py", line 218, in state
    return self.get_robot_state().json()
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/robot.py", line 176, in get_robot_state
    return self._message({'reqId': "1", 'cmd': "getRobotState"})
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/robot.py", line 62, in _message
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://nucleo.neatocloud.com/vendors/neato/robots/OPS#####-<12_HEX_DIGITS>/messages
```

**Comment by fermulator** [comment] 2019-02-17 02:51
Some suspect due to the newer standard of "OPS" prefix in the serial number.

**Comment by SeraphimSerapis** [comment] 2019-03-31 11:37
+1 on this:

```
Error during setup of component neato
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/neato/__init__.py", line 176, in setup
    hass.data[NEATO_LOGIN] = NeatoHub(hass, config[DOMAIN], Account)
  File "/usr/src/app/homeassistant/components/neato/__init__.py", line 200, in __init__
    self._hass.data[NEATO_ROBOTS] = self.my_neato.robots
  File "/usr/local/lib/python3.7/site-packages/pybotvac/account.py", line 64, in robots
    self.refresh_robots()
  File "/usr/local/lib/python3.7/site-packages/pybotvac/account.py", line 110, in refresh_robots
    endpoint=robot['nucleo_url']))
  File "/usr/local/lib/python3.7/site-packages/pybotvac/robot.py", line 43, in __init__
    if self.service_version not in SUPPORTED_SERVICES:
  File "/usr/local/lib/python3.7/site-packages/pybotvac/robot.py", line 226, in service_version
    return self.available_services['houseCleaning']
  File "/usr/local/lib/python3.7/site-packages/pybotvac/robot.py", line 222, in available_services
    return self.state['availableServices']
  File "/usr/local/lib/python3.7/site-packages/pybotvac/robot.py", line 218, in state
    return self.get_robot_state().json()
  File "/usr/local/lib/python3.7/site-packages/pybotvac/robot.py", line 176, in get_robot_state
    return self._message({'reqId': "1", 'cmd': "getRobotState"})
  File "/usr/local/lib/python3.7/site-packages/pybotvac/robot.py", line 62, in _message
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://nucleo.neatocloud.com/vendors/neato/robots/OPS18417-<DIGITS>/messages
```

**Comment by rogora** [comment] 2019-06-15 14:24
I think I had the same error, and solved it.
The problem is in robot.py, in the Auth class. _time.strftime_ is used to generate the authentication header, using whatever locale is set on the device executing the code. However, the authentication header must be created using the _en_US_ locale. 

My fix is to use the _en_US_ locale, which boils down to the following line added just before the call to  _time.strftime_:
        locale.setlocale(locale.LC_ALL, 'en_US.utf8')

Of course, you also need to _import locale_ in robot.py.

**Comment by fermulator** [comment] 2019-07-09 12:15
Indeed!

I am in Canada
```
>>> locale.getlocale()
('en_CA', 'UTF-8')
```

If we force it:
``` python
class Auth(requests.auth.AuthBase):
    """Create headers for request authentication"""

    def __init__(self, serial, secret):
        self.serial = serial
        self.secret = secret

    def __call__(self, request):
        # Due to https://github.com/stianaske/pybotvac/issues/30
        # Neato expects and supports authentication header ONLY for en_US
        locale.setlocale(locale.LC_ALL, 'en_US.utf8')
        date = time.strftime('%a, %d %b %Y %H:%M:%S', time.gmtime()) + ' GMT'

   # ...(snip)...
```

Confirming I'm loading my forked copy (`help('pybotvac')`)
```
Help on package pybotvac:

NAME
    pybotvac

PACKAGE CONTENTS
    account
    robot
    version

VERSION
    0.0.13

FILE
    /home/fermulator/projects/pybotvac/pybotvac/__init__.py
```

Then the test:
``` python
>>> for robot in pybotvac.Account(''<e-mail-SNIPPED>', '<password-SINPPED>').robots:
...   print(robot)
... 
Your 'FOO-NAME' robot is offline.
Name: BAR-NAME, Serial: OPS<SNIPPED>, Secret: <ALPHA_SNIPPED> Traits: ['maps']
```

**Comment by fermulator** [comment] 2019-07-09 12:44
Thanks @rogora , submitted this PR
https://github.com/stianaske/pybotvac/pull/42

**Comment by rogora** [comment] 2019-07-09 13:22
Glad to help. However, I'm not sure that setting the locale on each call is the ideal thing to do. Or maybe it is, but then it might be good to restore the previous locale after the call to `strftime`

**Comment by stianaske** [comment] 2019-07-12 08:42
Great work! Merged pull request and added code to reset locale after call to `strftime`.
Re-open ticket if the problem persists.

**Comment by fermulator** [comment] 2019-07-12 13:02
What is the release cycle for pybotvac?  I did a pull down from pip but still have version `0.13`, and I see that the version/init/setup aren't bumped.

I also tried manually applying the patch/fix into my venv site-packages, but it seems to add these weird "Conflicting" files...
```
(homeassistant) homeassistant@hass:~/.homeassistant$ ll /srv/homeassistant/lib/python3.6/site-packages/pybotvac
total 80
drwxr-xr-x   4 homeassistant homeassistant  4096 Jul 12 08:57 ./
drwxr-xr-x 173 homeassistant homeassistant 12288 Jul 12 08:38 ../
-rw-r--r--   1 homeassistant homeassistant  4020 Jul 12 08:38 account(Conflicted).py
-rw-r--r--   1 homeassistant homeassistant  4862 Jul 12 08:38 account.py
drwxr-xr-x   2 homeassistant homeassistant  4096 Jul 12 08:38 cert/
-rw-r--r--   1 homeassistant homeassistant    82 Jul 12 08:38 __init__(Conflicted 1).py
-rw-r--r--   1 homeassistant homeassistant    82 Jul 12 08:38 __init__(Conflicted).py
-rw-r--r--   1 homeassistant homeassistant    82 Jul 12 08:38 __init__.py
drwxr-xr-x   2 homeassistant homeassistant  4096 Jul 12 08:53 __pycache__/
-rw-r--r--   1 homeassistant homeassistant  7983 Jul 12 08:38 robot(Conflicted 1).py
-rw-r--r--   1 homeassistant homeassistant  8951 Jul 12 08:38 robot(Conflicted).py
-rw-r--r--   1 homeassistant homeassistant  9494 Jul 12 08:52 robot.py
```

Patch is applied
```
(homeassistant) homeassistant@hass:/srv/homeassistant/lib/python3.6/site-packages/pybotvac$ grep -rins locale *
Binary file __pycache__/robot.cpython-36.pyc matches
robot.py:7:import locale
robot.py:240:        locale.setlocale(locale.LC_ALL, 'en_US.utf8')
```

but it doesn't actually work (same error as before) - maybe I'm not allowed to raw-patch a file like this

(none-the-less, the fix itself helps when I test in a raw pull down of latest code base git pull + python import that package directly w/ the patch - so the patch is correct)

I manually pulled down the git repo into my venv site-packages (latest), and they worked

**Comment by stianaske** [comment] 2019-07-12 20:41
Wanted to do a bit more testing before releasing. If all looks good, I'll
try to find the time tomorrow.

**Comment by fermulator** [comment] 2019-07-13 12:08
Awesome. Apart from our discussion in https://github.com/stianaske/pybotvac/commit/4de740bab7288d60e36dc6f9215523e54b957564#commitcomment-34282061, which you'll address, I think it is good.

I tested it manually like this in my home-assistance instance too
``` python
        # Due to https://github.com/stianaske/pybotvac/issues/30
        # Neato expects and supports authentication header ONLY for en_US
        # Restore the current locale after the workaround is applied.
        saved_locale = locale.getlocale()
        locale.setlocale(locale.LC_ALL, 'en_US.utf8')

        date = time.strftime('%a, %d %b %Y %H:%M:%S', time.gmtime()) + ' GMT'

        locale.setlocale(locale.LC_ALL, saved_locale)
```

**Comment by fermulator** [comment] 2019-07-13 12:11
Anyone actually understand why this works?  I don't see any difference

``` python

>>> import locale
>>> import time
>>> date = time.strftime('%a, %d %b %Y %H:%M:%S', time.gmtime()) + ' GMT'
>>> print(date)
Sat, 13 Jul 2019 12:10:10 GMT
>>> 
>>> locale.setlocale(locale.LC_ALL, 'en_US.utf8')
'en_US.utf8'
>>> date = time.strftime('%a, %d %b %Y %H:%M:%S', time.gmtime()) + ' GMT'
>>> print(date)
Sat, 13 Jul 2019 12:10:26 GMT
```

**Comment by stianaske** [comment] 2019-07-13 18:45
I'm guessing the locale is already set to `en_US`? You can check with `print(locale.getlocale(locale.LC_ALL)` first.

**Comment by dshokouhi** [comment] 2019-07-13 19:33
I tried to bump the home assistant package but I am getting an error I am not sure how to resolve.

```
Traceback (most recent call last):
  File "/home/pi/home-assistant/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/home-assistant/homeassistant/components/neato/__init__.py", line 174, in setup
    hass.data[NEATO_LOGIN] = NeatoHub(hass, config[DOMAIN], Account)
  File "/home/pi/home-assistant/homeassistant/components/neato/__init__.py", line 198, in __init__
    self._hass.data[NEATO_ROBOTS] = self.my_neato.robots
  File "/home/pi/home-assistant/lib/python3.6/site-packages/pybotvac/account.py", line 65, in robots
    self.refresh_robots()
  File "/home/pi/home-assistant/lib/python3.6/site-packages/pybotvac/account.py", line 113, in refresh_robots
    endpoint=robot['nucleo_url']))
  File "/home/pi/home-assistant/lib/python3.6/site-packages/pybotvac/robot.py", line 46, in __init__
    if self.service_version not in SUPPORTED_SERVICES:
  File "/home/pi/home-assistant/lib/python3.6/site-packages/pybotvac/robot.py", line 231, in service_version
    return self.available_services['houseCleaning']
  File "/home/pi/home-assistant/lib/python3.6/site-packages/pybotvac/robot.py", line 227, in available_services
    return self.state['availableServices']
  File "/home/pi/home-assistant/lib/python3.6/site-packages/pybotvac/robot.py", line 223, in state
    return self.get_robot_state().json()
  File "/home/pi/home-assistant/lib/python3.6/site-packages/pybotvac/robot.py", line 181, in get_robot_state
    return self._message({'reqId': "1", 'cmd': "getRobotState"})
  File "/home/pi/home-assistant/lib/python3.6/site-packages/pybotvac/robot.py", line 63, in _message
    headers=self._headers)
  File "/home/pi/home-assistant/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/pi/home-assistant/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/home-assistant/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/home/pi/home-assistant/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/pi/home-assistant/lib/python3.6/site-packages/requests/models.py", line 317, in prepare
    self.prepare_auth(auth, url)
  File "/home/pi/home-assistant/lib/python3.6/site-packages/requests/models.py", line 548, in prepare_auth
    r = auth(self)
  File "/home/pi/home-assistant/lib/python3.6/site-packages/pybotvac/robot.py", line 244, in __call__
    saved_locale = locale.getlocale(locale.LC_ALL)
  File "/usr/local/lib/python3.6/locale.py", line 580, in getlocale
    raise TypeError('category LC_ALL is not supported')
TypeError: category LC_ALL is not supported
```

@fermulator did you have to make more changes to the `neato` package?  Trying to add multiple floorplan support here :) https://github.com/dshokouhi/hass-neato-custom-component/tree/multiple_floorplans

**Comment by stianaske** [comment] 2019-07-13 19:51
@dshokouhi I see that this is mentioned in the [manual](https://docs.python.org/3.7/library/locale.html#locale.getlocale):

> Returns the current setting for the given locale category as sequence containing language code, encoding. category may be one of the LC_* values _except LC_ALL_. It defaults to LC_CTYPE.

I'm not sure why it seems to work on my computer though.

Could you try changing the type to `LC_TIME`? I guess that should solve it?

**Comment by dshokouhi** [comment] 2019-07-13 19:56
@stianaske that was a quick fix :) changing line 244 to allowed the component to load :)

```
saved_locale = locale.getlocale(locale.LC_TIME)
```

**Comment by stianaske** [comment] 2019-07-13 19:58
@dshokouhi I'll make a new release right away then.

**Comment by stianaske** [comment] 2019-07-13 20:08
[v0.0.15](https://github.com/stianaske/pybotvac/releases/tag/v0.0.15) hopefully resolves this. As my robot appears to have broken down (finally an excuse to upgrade?) I am unable to test the release properly. Please let me know if you find any issues.

**Closed as completed** 2019-07-13 20:08 UTC

**Comment by fermulator** [comment] 2019-07-17 12:15
@stianaske @dshokouhi 

yes you can't do getlocal() on LC_ALL

I did this

``` python
        # Due to https://github.com/stianaske/pybotvac/issues/30
        # Neato expects and supports authentication header ONLY for en_US
        # Restore the current locale after the workaround is applied.
        saved_locale = locale.getlocale()
        locale.setlocale(locale.LC_ALL, 'en_US.utf8')

        date = time.strftime('%a, %d %b %Y %H:%M:%S', time.gmtime()) + ' GMT'

        locale.setlocale(locale.LC_ALL, saved_locale)
```
(same as above)

The default of `LC_CTYPE` seemed to work fine for me.
https://docs.python.org/3/library/locale.html#locale.getlocale

But changing it to get the `LC_TIME` is probably fine as well.

**Comment by fermulator** [comment] 2019-07-18 12:33
fwiw, the v0.0.15 tag that delivers this fix I am proposing bump for home-assistant in 
https://github.com/home-assistant/home-assistant/pull/25250

**Comment by dshokouhi** [comment] 2019-07-18 15:59
@fermulator not sure if you saw but I had submitted a PR yesterday with this library bump, a fix for zone cleaning and Vorwerk support.  Should hopefully get merged soon since its already approved.

**Comment by fermulator** [comment] 2019-08-14 13:42
NOTE: the fix here is not completely understood - I submitted a support ticket into Neato 5 weeks ago, and is pending response from their development team into why the API is requiring `en_US` locale. (support ticket ID = 704532) @ostinelli if you can help?
